import Header from "./components/Header/Header";
import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className="flex flex-col items-center bg-gray-950">
        <Header />
        {children}
      </body>
    </html>
  );
}
